// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Achievement struct {
	Achievementid int32
	Name          string
	Obtaineddate  sql.NullTime
	Contributorid sql.NullInt32
	Rank          sql.NullInt32
}

type Client struct {
	Clientid            int32
	Name                string
	Address             sql.NullString
	Responsiblepersonid sql.NullInt32
	Contactpersonid     sql.NullInt32
	Officephone         sql.NullString
	Mobilephone         sql.NullString
	Email               sql.NullString
}

type Coworker struct {
	Coworkerid   int32
	Name         string
	Officephone  sql.NullString
	Mobilephone  sql.NullString
	Emailaddress sql.NullString
}

type Director struct {
	Directorid int32
	Labid      sql.NullInt32
	Startdate  sql.NullTime
	Term       sql.NullInt32
}

type Equipment struct {
	Equipmentid  int32
	Name         string
	Purchasedate sql.NullTime
	Status       sql.NullString
}

type Equipmentreservation struct {
	Reservationid int32
	Equipmentid   sql.NullInt32
	Researcherid  sql.NullInt32
	Starttime     sql.NullTime
	Endtime       sql.NullTime
}

type Laboratory struct {
	Labid             int32
	Name              string
	Officearea        sql.NullFloat64
	Address           sql.NullString
	Researchdirection sql.NullString
}

type Office struct {
	Officeid int32
	Labid    sql.NullInt32
	Area     sql.NullFloat64
	Address  sql.NullString
}

type Paper struct {
	Paperid int32
}

type Partner struct {
	Partnerid           int32
	Name                string
	Address             sql.NullString
	Responsiblepersonid sql.NullInt32
	Contactperson       sql.NullString
	Officephone         sql.NullString
	Mobilephone         sql.NullString
	Email               sql.NullString
}

type Patent struct {
	Patentid int32
	Type     sql.NullString
}

type Project struct {
	Projectid       int32
	Leaderid        sql.NullInt32
	Name            string
	Researchcontent sql.NullString
	Totalfunds      sql.NullFloat64
	Startdate       sql.NullTime
	Enddate         sql.NullTime
	Clientid        sql.NullInt32
}

type Projectachievement struct {
	Projectid     int32
	Achievementid int32
}

type Projectpartner struct {
	Projectid           int32
	Partnerid           int32
	Responsiblepersonid sql.NullInt32
}

type Projectresearcher struct {
	Projectid       int32
	Researcherid    int32
	Joindate        sql.NullTime
	Workload        sql.NullFloat64
	Disposablefunds sql.NullFloat64
}

type Qualitymonitor struct {
	Monitorid         int32
	Name              string
	Address           sql.NullString
	Responsibleperson sql.NullString
	Contactpersonid   sql.NullInt32
}

type Researcher struct {
	Researcherid      int32
	Labid             sql.NullInt32
	Name              string
	Gender            string
	Title             string
	Age               int32
	Researchdirection sql.NullString
	Leader            bool
}

type Role struct {
	Roleid   int32
	Rolename string
}

type Secretary struct {
	Secretaryid      int32
	Name             string
	Gender           sql.NullString
	Age              sql.NullInt32
	Employmentdate   sql.NullTime
	Responsibilities sql.NullString
}

type Secretaryservice struct {
	Secretaryid int32
	Labid       int32
}

type Softwareright struct {
	Softwarerightid int32
}

type Subtopic struct {
	Subtopicid          int32
	Projectid           sql.NullInt32
	Leaderid            sql.NullInt32
	Enddaterequirement  sql.NullTime
	Disposablefunds     sql.NullFloat64
	Technicalindicators sql.NullString
}

type User struct {
	Userid   uuid.UUID
	Username string
	Password string
	Email    sql.NullString
}

type Userrole struct {
	Userid uuid.UUID
	Roleid int32
}
