// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"database/sql"
	"time"
)

type Achievement struct {
	Achievementid int32
	Name          string
	Obtaineddate  time.Time
	Contributorid int32
	Baseproject   int32
	Basesubtopic  sql.NullInt32
	Rank          int32
}

type Client struct {
	Clientid int32
	Name     string
	Address  string
	// 委托方负责人
	Leaderid    int32
	Officephone string
}

type Contact struct {
	Contactid    int32
	Name         string
	Officephone  string
	Mobilephone  string
	Emailaddress string
	Baseclient   sql.NullInt32
	Basepartners sql.NullInt32
	Baseqm       sql.NullInt32
}

type Director struct {
	Directorid int32
	Labid      int32
	Startdate  time.Time
	Term       int32
}

type Equipment struct {
	Equipmentid  int32
	Name         string
	Purchasedate sql.NullTime
	Available    bool
}

type Equipmentreservation struct {
	Reservationid int32
	Equipmentid   sql.NullInt32
	Researcherid  sql.NullInt32
	Starttime     sql.NullTime
	Endtime       sql.NullTime
}

type Laboratory struct {
	Labid             int32
	Name              string
	Directorid        int32
	Officearea        float64
	Address           string
	Researchdirection sql.NullString
}

type Leader struct {
	Leaderid     int32
	Name         string
	Officephone  sql.NullString
	Mobilephone  sql.NullString
	Emailaddress sql.NullString
}

type Office struct {
	Officeid  int32
	Labid     int32
	Area      float64
	Address   string
	Managerid int32
}

type Paper struct {
	Paperid int32
}

type Partner struct {
	Partnerid int32
	Name      string
	Address   string
	// 合作方负责人
	Leaderid    int32
	Officephone string
}

type Patent struct {
	Patentid int32
	Type     string
}

type Project struct {
	Projectid         int32
	Peojectleader     int32
	Name              string
	Researchcontent   sql.NullString
	Totalfunds        float64
	Startdate         time.Time
	Enddate           time.Time
	Qualitymonitorsid int32
	Clientid          int32
}

type Projectachievement struct {
	Projectid     int32
	Achievementid int32
}

type Projectpartner struct {
	Projectid int32
	Partnerid int32
}

type Projectresearcher struct {
	Projectid       int32
	Researcherid    int32
	Joindate        time.Time
	Workload        float64
	Disposablefunds float64
}

type Qualitymonitor struct {
	Monitorid int32
	Name      string
	Address   string
	Leaderid  int32
}

type Researcher struct {
	Researcherid      int32
	Labid             int32
	Researchnumber    int32
	Name              string
	Gender            string
	Title             string
	Age               int32
	Emailaddress      string
	Researchdirection string
	Leader            bool
}

type Secretary struct {
	Secretaryid  int32
	Name         string
	Gender       string
	Age          int32
	Mobilephone  string
	Emailaddress string
}

type Secretaryservice struct {
	Secretaryid      int32
	Labid            int32
	Employmentdate   time.Time
	Responsibilities string
}

type Softwareright struct {
	Softwarerightid int32
}

type Subtopic struct {
	Subtopicid int32
	Projectid  int32
	Leaderid   int32
	// DDL日期
	Enddaterequirement  time.Time
	Disposablefunds     float64
	Technicalindicators string
}

type User struct {
	Userid   int32
	Username string
	Password string
	Roleid   int32
}
