// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: stakeholder.sql

package database

import (
	"context"
	"database/sql"
)

const createClient = `-- name: CreateClient :one

INSERT INTO clients (name, address, officephone, leaderid) VALUES ($1, $2, $3, $4) RETURNING clientid
`

type CreateClientParams struct {
	Name        string
	Address     string
	Officephone string
	Leaderid    int32
}

// ClientPart
func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.Name,
		arg.Address,
		arg.Officephone,
		arg.Leaderid,
	)
	var clientid int32
	err := row.Scan(&clientid)
	return clientid, err
}

const createContact = `-- name: CreateContact :one

INSERT INTO contacts (name, officephone, mobilephone, emailaddress) VALUES ($1, $2, $3, $4) RETURNING contactid
`

type CreateContactParams struct {
	Name         string
	Officephone  string
	Mobilephone  string
	Emailaddress string
}

// ContactsPart
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createContact,
		arg.Name,
		arg.Officephone,
		arg.Mobilephone,
		arg.Emailaddress,
	)
	var contactid int32
	err := row.Scan(&contactid)
	return contactid, err
}

const createLeader = `-- name: CreateLeader :one

INSERT INTO leaders (name, officephone, mobilephone, emailaddress) VALUES ($1, $2, $3, $4) RETURNING leaderid
`

type CreateLeaderParams struct {
	Name         string
	Officephone  string
	Mobilephone  string
	Emailaddress string
}

// LeaderPart
func (q *Queries) CreateLeader(ctx context.Context, arg CreateLeaderParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createLeader,
		arg.Name,
		arg.Officephone,
		arg.Mobilephone,
		arg.Emailaddress,
	)
	var leaderid int32
	err := row.Scan(&leaderid)
	return leaderid, err
}

const createPartner = `-- name: CreatePartner :one

INSERT INTO partners (name, address, officephone, leaderid) VALUES ($1, $2, $3, $4) RETURNING partnerid
`

type CreatePartnerParams struct {
	Name        string
	Address     string
	Officephone string
	Leaderid    int32
}

// PartnerPart
func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createPartner,
		arg.Name,
		arg.Address,
		arg.Officephone,
		arg.Leaderid,
	)
	var partnerid int32
	err := row.Scan(&partnerid)
	return partnerid, err
}

const createQM = `-- name: CreateQM :one

INSERT INTO qualitymonitors (name, address, leaderid) VALUES ($1, $2, $3) RETURNING monitorid
`

type CreateQMParams struct {
	Name     string
	Address  string
	Leaderid int32
}

// QMPart
func (q *Queries) CreateQM(ctx context.Context, arg CreateQMParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createQM, arg.Name, arg.Address, arg.Leaderid)
	var monitorid int32
	err := row.Scan(&monitorid)
	return monitorid, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE clientid = $1
`

func (q *Queries) DeleteClient(ctx context.Context, clientid int32) error {
	_, err := q.db.ExecContext(ctx, deleteClient, clientid)
	return err
}

const deleteLeader = `-- name: DeleteLeader :exec
DELETE FROM leaders WHERE leaderid = $1
`

func (q *Queries) DeleteLeader(ctx context.Context, leaderid int32) error {
	_, err := q.db.ExecContext(ctx, deleteLeader, leaderid)
	return err
}

const deletePartner = `-- name: DeletePartner :exec
DELETE FROM partners WHERE partnerid = $1
`

func (q *Queries) DeletePartner(ctx context.Context, partnerid int32) error {
	_, err := q.db.ExecContext(ctx, deletePartner, partnerid)
	return err
}

const deleteQM = `-- name: DeleteQM :exec
DELETE FROM qualitymonitors WHERE monitorid = $1
`

func (q *Queries) DeleteQM(ctx context.Context, monitorid int32) error {
	_, err := q.db.ExecContext(ctx, deleteQM, monitorid)
	return err
}

const getClient = `-- name: GetClient :one
SELECT clientid, name, address, leaderid, officephone FROM clients WHERE clientid = $1
`

func (q *Queries) GetClient(ctx context.Context, clientid int32) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, clientid)
	var i Client
	err := row.Scan(
		&i.Clientid,
		&i.Name,
		&i.Address,
		&i.Leaderid,
		&i.Officephone,
	)
	return i, err
}

const getLeader = `-- name: GetLeader :one
SELECT leaderid, name, officephone, mobilephone, emailaddress FROM leaders WHERE leaderid = $1
`

func (q *Queries) GetLeader(ctx context.Context, leaderid int32) (Leader, error) {
	row := q.db.QueryRowContext(ctx, getLeader, leaderid)
	var i Leader
	err := row.Scan(
		&i.Leaderid,
		&i.Name,
		&i.Officephone,
		&i.Mobilephone,
		&i.Emailaddress,
	)
	return i, err
}

const getPartner = `-- name: GetPartner :one
SELECT partnerid, name, address, leaderid, officephone FROM partners WHERE partnerid = $1
`

func (q *Queries) GetPartner(ctx context.Context, partnerid int32) (Partner, error) {
	row := q.db.QueryRowContext(ctx, getPartner, partnerid)
	var i Partner
	err := row.Scan(
		&i.Partnerid,
		&i.Name,
		&i.Address,
		&i.Leaderid,
		&i.Officephone,
	)
	return i, err
}

const getQMById = `-- name: GetQMById :one
SELECT monitorid, name, address, leaderid FROM qualitymonitors WHERE monitorid = $1
`

func (q *Queries) GetQMById(ctx context.Context, monitorid int32) (Qualitymonitor, error) {
	row := q.db.QueryRowContext(ctx, getQMById, monitorid)
	var i Qualitymonitor
	err := row.Scan(
		&i.Monitorid,
		&i.Name,
		&i.Address,
		&i.Leaderid,
	)
	return i, err
}

const listClient = `-- name: ListClient :one
SELECT clientid, name, address, leaderid, officephone FROM clients
`

func (q *Queries) ListClient(ctx context.Context) (Client, error) {
	row := q.db.QueryRowContext(ctx, listClient)
	var i Client
	err := row.Scan(
		&i.Clientid,
		&i.Name,
		&i.Address,
		&i.Leaderid,
		&i.Officephone,
	)
	return i, err
}

const listPartner = `-- name: ListPartner :many
SELECT partnerid, name, address, leaderid, officephone FROM partners
`

func (q *Queries) ListPartner(ctx context.Context) ([]Partner, error) {
	rows, err := q.db.QueryContext(ctx, listPartner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partner
	for rows.Next() {
		var i Partner
		if err := rows.Scan(
			&i.Partnerid,
			&i.Name,
			&i.Address,
			&i.Leaderid,
			&i.Officephone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQM = `-- name: ListQM :one
SELECT monitorid, name, address, leaderid FROM qualitymonitors
`

func (q *Queries) ListQM(ctx context.Context) (Qualitymonitor, error) {
	row := q.db.QueryRowContext(ctx, listQM)
	var i Qualitymonitor
	err := row.Scan(
		&i.Monitorid,
		&i.Name,
		&i.Address,
		&i.Leaderid,
	)
	return i, err
}

const setContactClient = `-- name: SetContactClient :one
UPDATE contacts SET baseclient = $1 WHERE contactid = $2 RETURNING contactid
`

type SetContactClientParams struct {
	Baseclient sql.NullInt32
	Contactid  int32
}

func (q *Queries) SetContactClient(ctx context.Context, arg SetContactClientParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, setContactClient, arg.Baseclient, arg.Contactid)
	var contactid int32
	err := row.Scan(&contactid)
	return contactid, err
}

const setContactPartner = `-- name: SetContactPartner :one
UPDATE contacts SET basepartners = $1 WHERE contactid = $2 RETURNING contactid
`

type SetContactPartnerParams struct {
	Basepartners sql.NullInt32
	Contactid    int32
}

func (q *Queries) SetContactPartner(ctx context.Context, arg SetContactPartnerParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, setContactPartner, arg.Basepartners, arg.Contactid)
	var contactid int32
	err := row.Scan(&contactid)
	return contactid, err
}

const setContactQM = `-- name: SetContactQM :one
UPDATE contacts SET baseqm = $1 WHERE contactid = $2 RETURNING contactid
`

type SetContactQMParams struct {
	Baseqm    sql.NullInt32
	Contactid int32
}

func (q *Queries) SetContactQM(ctx context.Context, arg SetContactQMParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, setContactQM, arg.Baseqm, arg.Contactid)
	var contactid int32
	err := row.Scan(&contactid)
	return contactid, err
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients SET name = $1, address = $2, officephone = $3, leaderid = $4 WHERE clientid = $5 RETURNING clientid, name, address, leaderid, officephone
`

type UpdateClientParams struct {
	Name        string
	Address     string
	Officephone string
	Leaderid    int32
	Clientid    int32
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.Name,
		arg.Address,
		arg.Officephone,
		arg.Leaderid,
		arg.Clientid,
	)
	var i Client
	err := row.Scan(
		&i.Clientid,
		&i.Name,
		&i.Address,
		&i.Leaderid,
		&i.Officephone,
	)
	return i, err
}
