// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: user.sql

package database

import (
	"context"
)

const adminLogin = `-- name: AdminLogin :one
SELECT userid, username, password, roleid FROM Users WHERE Role = 'admin' AND Username = $1 AND Password = $2 LIMIT 1
`

type AdminLoginParams struct {
	Username string
	Password string
}

func (q *Queries) AdminLogin(ctx context.Context, arg AdminLoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, adminLogin, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Username,
		&i.Password,
		&i.Roleid,
	)
	return i, err
}
