// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: user.sql

package database

import (
	"context"
)

const login = `-- name: Login :one
SELECT userid, username, password, roleid FROM Users WHERE Username = $1 AND Password = $2 LIMIT 1
`

type LoginParams struct {
	Username string
	Password string
}

func (q *Queries) Login(ctx context.Context, arg LoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, login, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Username,
		&i.Password,
		&i.Roleid,
	)
	return i, err
}
